### ISSUE TITLE
PyBoltz Installation Help

### ISSUE THREAD

**Issue by siwoo926** [UTA-REST/PyBoltz#16]
Hi,

I've followed the installation guide on github but I'm having troubles running the setup.sh files for both PyBoltz and PyGasMix. I've tried both on Windows using Cygwin/Git Bash, and running it via Ubuntu as a subsystem of my laptop.  I get a few different errors when trying to run 

warning: PyGasMix/Gas.pxd:4:15: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line. 

[Errno 13] Permission denied: '/home/PyGasMix/PyGasMix/Gases/ARGON.c'                                                                                                                                              Traceback (most recent call last):                                                                                                                                                                                   File "/home/sk5717/.local/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1208, in cythonize_one                                                                                                     result = compile_single(pyx_file, options, full_module_name=full_module_name)                                                                                                                                    File "/home/sk5717/.local/lib/python3.8/site-packages/Cython/Compiler/Main.py", line 727, in compile_single                                                                                                          return run_pipeline(source, options, full_module_name)      

PermissionError: [Errno 13] Permission denied: '/home/PyGasMix/PyGasMix/Gases/ARGON.c'                                                                                                                             Traceback (most recent call last):                                                                                                                                                                                   File "setup_build.py", line 34, in <module>                                                                                                                                                                          setup(ext_modules=cythonize(extensions))                                                                                                                                                                         File "/home/sk5717/.local/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize                                                                                                         cythonize_one(*args)                                                                                                                                                                                             File "/home/sk5717/.local/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one                                                                                                     raise CompileError(None, pyx_file)

I'm relatively new to using Linux and this sort of thing so I may just be messing up somewhere without knowing. I'm also using slightly more recent versions of the software/packages
Python 3.8.5
Cython 0.29.21
Numpy 1.19.4
which may be causing the errors?
Any help would be much appreciated
Many thanks

**Comment by xia-stan** [comment]
I ran into a similar problem. There seems to be an issue with the setup.py files not resolving dependencies properly. I managed to work around the problem with the following bash script: 
```bash
#!/usr/bin/env bash

python3 -m venv venv && \
source venv/bin/activate && \
pip3 install --upgrade pip setuptools wheel && \
pip3 install -r numpy Cython && \
pip3 install git+https://github.com/UTA-REST/PyGasMix.git && \
pip3 install git+https://github.com/UTA-REST/PyBoltz.git
```
---
### System Config
* Windows 11
* WSL w/ Debian 11
* Python 3.9.2
